quick_links:
  type: objects
  default:
    [
      { "question": "How do I make a custom badge?" },
      { "question": "How do I install themes?" },
      { "question": "What are trust levels?" },
    ]
  schema:
    name: "link"
    identifier: question
    properties:
      question:
        type: string
        required: true
